security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_database:
            entity:
                class: App\Domain\Usuario\Entity\Usuario
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/usuario/login
            stateless: true
            provider: users_in_database
            json_login:
                check_path: /api/usuario/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        registrar:
            pattern: ^/api/usuario/registrar
            stateless: true
            security: false
        
        api:
            pattern: ^/api
            stateless: true
            provider: users_in_database
            jwt: ~

    access_control:
        - { path: ^/api/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/usuario/registrar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
