framework:
    validation:
        enabled: true
        mapping:
            paths:
                - '%kernel.project_dir%/config/infrastructure/validator'

when@test:
    framework:
        validation:
            not_compromised_password: false
