controllers:
    resource:
        path: ../src/Presentation/
        namespace: App\Presentation
    type: attribute
    
api_login_check:
    path: /api/usuario/login

app.swagger_ui:
    path: /swagger/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /swagger/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }